# Generated by Django 5.0.3 on 2024-04-19 20:22

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerente_nome', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('gerente_matricula', models.CharField(max_length=250, verbose_name='Matrícula')),
                ('gerente_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('gerente_celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('gerente_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'gerentes',
                'verbose_name_plural': 'gerentes',
                'db_table': 'gerentes',
                'ordering': ('gerente_nome',),
            },
        ),
    ]
