# Generated by Django 5.0.3 on 2024-04-15 23:04

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_cnes', models.CharField(max_length=250, verbose_name='CNES')),
                ('uni_nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('uni_cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('uni_endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('uni_num_casa', models.CharField(max_length=250, verbose_name='Número')),
                ('uni_bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('uni_cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('uni_uf', localflavor.br.models.BRStateField(max_length=2, verbose_name='UF')),
                ('uni_cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('uni_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('uni_tipo', models.CharField(choices=[('Upa', 'Upa'), ('Ubs', 'Ubs'), ('Hospital', 'Hospital'), ('Maternidade', 'Maternidade')], max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'unidade_saude',
                'verbose_name_plural': 'unidade_saude',
                'db_table': 'unidade_saude',
                'ordering': ('uni_cnes',),
            },
        ),
    ]
