# Generated by Django 5.0.3 on 2024-04-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_pais_pai_rg'),
        ('unidade_saude', '0001_initial'),
        ('vacina', '0002_vacina_vacina_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroVacinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(verbose_name='Data da aplicação')),
                ('status', models.CharField(choices=[('Processamento', 'Processamento'), ('Completo', 'Completo'), ('Recusado', 'Recusado')], max_length=250, verbose_name='Status')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.crianca')),
                ('unidade_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade_saude.unidadesaude')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacina.vacina')),
            ],
            options={
                'verbose_name': 'vacinacao',
                'verbose_name_plural': 'vacinacao',
                'db_table': 'vacinacao',
            },
        ),
    ]
