# Generated by Django 5.0.3 on 2024-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrovacinal',
            name='fabricante',
            field=models.CharField(blank=True, max_length=250, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='cadastrovacinal',
            name='lote',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lote'),
        ),
    ]
