# Generated by Django 5.0.3 on 2024-04-06 00:01

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_nome', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('pai_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('pai_celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('pai_cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('pai_endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('pai_num_casa', models.CharField(max_length=250, verbose_name='Número')),
                ('pai_complemento_casa', models.CharField(blank=True, max_length=250, verbose_name='Complemento')),
                ('pai_bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('pai_cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('pai_uf', localflavor.br.models.BRStateField(max_length=2, verbose_name='UF')),
                ('pai_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'db_table': 'pais',
                'ordering': ('pai_nome',),
            },
        ),
    ]
