# Generated by Django 5.0.3 on 2024-04-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_crianca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('pai_nome',), 'verbose_name': 'pais', 'verbose_name_plural': 'pais'},
        ),
    ]
