# Generated by Django 5.0.3 on 2024-04-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_pais_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='pai_rg',
            field=models.CharField(default=1234, max_length=250, verbose_name='RG'),
            preserve_default=False,
        ),
    ]
