# Generated by Django 5.0.3 on 2024-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacina_nome', models.CharField(max_length=250, verbose_name='Vacina')),
                ('vacina_lote', models.CharField(max_length=250, verbose_name='Lote')),
            ],
        ),
    ]
