# Generated by Django 5.0.3 on 2024-04-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0002_vacina_vacina_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='vacina_fabricante',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vacina_lote',
            field=models.CharField(blank=True, max_length=250, verbose_name='Lote'),
        ),
    ]
