# Generated by Django 5.0.3 on 2024-04-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0004_calendariovacina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarioVacina',
        ),
    ]
