# Generated by Django 5.0.3 on 2024-04-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0006_calendariovacina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariovacina',
            name='calendario_idade',
            field=models.CharField(max_length=20, verbose_name='Idade em dias'),
        ),
        migrations.AlterField(
            model_name='calendariovacina',
            name='calendario_vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacina.vacina', verbose_name='Vacina'),
        ),
    ]
