# Generated by Django 5.0.3 on 2024-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0007_alter_calendariovacina_calendario_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariovacina',
            name='calendario_dose',
            field=models.CharField(choices=[('1ª dose', '1ª dose'), ('2ª dose', '2ª dose'), ('3ª dose', '3ª dose'), ('4ª dose', '4ª dose'), ('5ª dose', '5ª dose'), ('6ª dose', '6ª dose'), ('dose unica', 'dose unica'), ('reforço', 'reforço')], max_length=20, verbose_name='Dose'),
        ),
    ]
